### ISSUE TITLE
Dynamic Decons_ID51_Meenaloshine.S.P_9344362027_spmeenaloshine@gmail.com

### ISSUE THREAD

**Issue by Amarnathkerala** [Akilandeswari/Sona_IDEATHON_2021#7]
**Team Name:**

**Team ID:**

**Team Leader's Name:**

**Team Leader's Contact Number:**

**Team Leader's Mail id:**

**Names of the Team Members - Contact Number - Mail id**

(Add each of the team members' details in the above format one by one)

**For competition 1**

1. Study.doc
2. Questionnaire.doc
3. Profile_respondents.doc
4. findings.doc
5. proposed_solution.doc

**For competition 2 - Round 1**

1. Source code of the app
2. Data Flow diagram
3. Video walkthrough of the app
4. Help document

**Comment by Amarnathkerala** [comment]
[DOCUMENT -1 AVAILABLE SOLUTIONS FOR COVID-19.docx](https://github.com/Akilandeswari/Sona_IDEATHON_2021/files/6440009/DOCUMENT.-1.AVAILABLE.SOLUTIONS.FOR.COVID-19.docx)

**Comment by Amarnathkerala** [comment]
[DOCUMENT-2 AVAILABLE FINDINGS AND INTERPRETATIONS FOR COVID-19.docx](https://github.com/Akilandeswari/Sona_IDEATHON_2021/files/6440011/DOCUMENT-2.AVAILABLE.FINDINGS.AND.INTERPRETATIONS.FOR.COVID-19.docx)
[DOCUMENT-3 TECHNOLOGICAL SOLUTIONS FOR COVID-19 (1).docx](https://github.com/Akilandeswari/Sona_IDEATHON_2021/files/6440014/DOCUMENT-3.TECHNOLOGICAL.SOLUTIONS.FOR.COVID-19.1.docx)

**Comment by Akilandeswari** [comment]
Please enter all the details in the issue format and resubmit the issue (commit changes) No details are available.
